#!/bin/bash

# 1. Install oh-my-zsh
if [ ! -f ~/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# 2. Change shell to zsh
chsh -s /bin/zsh

# 3. Create symbolic links
if [ -f ~/.zshrc ]; then
    rm -rf ~/.zshrc
    ln -s ~/.dotfiles/zsh/zshrc ~/.zshrc
fi
if [ -f ~/.inputrc ]; then
    rm -rf ~/.inputrc
    ln -s ~/.dotfiles/inputrc ~/.inputrc
fi
if [ -f ~/.tmux.conf ]; then
    rm -rf ~/.tmux.conf
    ln -s ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf
fi
