#!/bin/bash

# 1. Install oh-my-zsh
if [ ! -f ~/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# 2. Change shell to zsh
chsh -s /bin/zsh

# 2. Create symbolic links
ln -s ~/.dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/.dotfiles/inputrc ~/.inputrc
ln -s ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf
