# path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# in iTerm2 use agnoster, otherwise kolo
if [[ $TERM_PROGRAM == *"iTerm"* ]] || [[ $TERM == *"italic"* ]]; then
    ZSH_THEME="agnoster"
else
    ZSH_THEME="kolo"
fi

# plugins
plugins=(git, brew, osx, sudo, extract)

source $ZSH/oh-my-zsh.sh

source ~/.dotfiles/zsh/zshrc-deisu

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
